version: "3.7"

services:
  api:
    container_name: ${APP_NAME}_api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    tty: true
    ports:
      - "80:3000"
    volumes:
      - "./packages/api:/api"

  db:
    container_name: ${APP_NAME}_db
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      TZ: "Asia/Tokyo"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
    name: ${APP_NAME}_db
    driver: local
